apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kernelapi-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kernelapi
    spec:
      containers:
      - name: kernelapi
        image: ipsacr.azurecr.io/kernelapi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ipsSecret
      
       
---
apiVersion: v1
kind: Service
metadata:
  name: kernelapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kernelapi